name: Backend Directus Extension Build

on:
  push:
    branches: [master]
    paths:
      - 'apps/backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ§° Setup Node.js, Yarn & Dependencies
        uses: ./.github/actions/setup-and-install
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸš€ Build the extension
        run: yarn run build

      - name: ğŸ” Check if dist has changed
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain ./dist) ]]; then
            echo "dist_changed=true" >> $GITHUB_ENV
          else
            echo "dist_changed=false" >> $GITHUB_ENV
          fi

      - name: âœ… Commit and push changes if dist changed
        if: env.dist_changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase
          git add -f ./dist
          git commit -m "Update dist after backend build"
          git push

      - name: â˜ï¸ Upload Dist Artifact
        if: env.dist_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: backend-dist
